services:
  - type: web
    name: sistema-pdv-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm rebuild better-sqlite3 && npm run build && ls -la dist
    startCommand: node backend/start.js
    envVars:
      - key: NODE_ENV
        value: production
