services:
  - type: web
    name: sistema-pdv-backend
    env: node
    plan: free
    buildCommand: npm install && cd backend && npm install && npm run build
    startCommand: cd backend && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
